name: 360eventsAustralia
favicon: null
layout_spectrum: 0.49964673165231943
typography_spectrum: 0.5686544885393232
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.8841960886493325
  lightness: 0.02624974073842168
  saturation: 0.4427234136965126
  rhythmicContrast: 0.2218914891127497
purpose: []
